run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gocritic
    - revive
    - goconst
    - gosec
    - nakedret
    - copyloopvar

linters-settings:
  errcheck:
    check-blank: true
  govet:
    enable:
      - shadow
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/pfrederiksen/blast-radius
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  revive:
    rules:
      - name: exported
        disabled: false
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - gocritic
        - unparam
    # Exclude known false positives
    - linters:
        - staticcheck
      text: "SA1019:" # ignore deprecation warnings for now
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
